package de.hawh.ld.denksport;

/*
* In Zeile 12 geht der Compiler davon aus, dass nach \_u (ohne den Unterstrich) Unicode kommt.
* "nits" ist aber kein Unicode. Dadurch folg, auch in Kommentaren, ein Compilerfehler.
*/



/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * from F:\TestRoot\apps\a1\_units\include\PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o’clock AM GMT+00:00
 */
public class Test {
    public static void main(String[] args) {
        System.out.print("Hell");
        System.out.println("o world");
    }
}


